name: Build

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
      os:
        required: true
        type: string
      setupCommand:
        required: true
        type: string
      buildArgs:
        required: true
        type: string
      artifactName:
        required: true
        type: string
      artifactPath:
        required: true
        type: string

env:
  HAXE_VERSION: 4.3.7
  PROJECT_NAME: PsychEngine

jobs:
  build:
    name: Build
    runs-on: ${{ inputs.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: ${{ env.HAXE_VERSION }}

      - name: Setup Android NDK
        if: inputs.name == 'Android'
        id: setup-ndk
        uses: nttld/setup-ndk@main
        with:
          ndk-version: r27c
          add-to-path: false

      - name: Install Libraries
        run: |
          haxelib git lime https://github.com/SatoruSam/lime
          haxelib run lime setup
          haxelib install flixel-addons 3.2.2
          haxelib install tjson 1.4.0
          haxelib git flxanimate https://github.com/Dot-Stuff/flxanimate
          haxelib git openfl https://github.com/SatoruSam/openfl
          haxelib git flixel https://github.com/SatoruSam/flixel
          haxelib git flixel-ui https://github.com/SatoruSam/flixel-ui
          haxelib git hxcpp https://github.com/SatoruSam/hxcpp
          haxelib git SScript https://github.com/SatoruSam/SScript
          haxelib install hxdiscord_rpc
          haxelib git hxluajit https://github.com/SatoruSam/hxluajit
          haxelib install hxgamemode
          haxelib install linc_luajit
          haxelib install hscript-iris 1.1.3
          haxelib git format https://github.com/SatoruSam/format
          haxelib git hxp https://github.com/SatoruSam/hxp
          haxelib git hxvlc https://github.com/SatoruSam/hxvlc

      - name: Configure Android
        if: inputs.name == 'Android'
        run: |
          haxelib run lime config ANDROID_SDK $ANDROID_HOME
          haxelib run lime config ANDROID_NDK_ROOT ${{ steps.setup-ndk.outputs.ndk-path }}
          haxelib run lime config JAVA_HOME $JAVA_HOME_21_arm64
          haxelib run lime config ANDROID_SETUP true

      - name: Compile
        if: inputs.name == 'Android'
        run: haxelib run lime build android ${{ inputs.buildArgs }} -D ${{ inputs.assetType }}

      - name: Upload Artifact
        uses: actions/upload-artifact@main
        with:
          name: ${{ inputs.artifactName }}
          path: ${{ inputs.artifactPath }}
          if-no-files-found: error
