name: Build

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
      os:
        required: true
        type: string
      setupCommand:
        required: true
        type: string
      buildArgs:
        required: true
        type: string
      artifactName:
        required: true
        type: string
      artifactPath:
        required: true
        type: string

env:
  HAXE_VERSION: 4.3.2
  PROJECT_NAME: NeuroEngine

jobs:
  build:
    name: Build
    runs-on: ${{ inputs.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Haxe
        uses: krdlab/setup-haxe@v1
        with:
          haxe-version: ${{ env.HAXE_VERSION }}

      - name: Cache Haxelib
        uses: actions/cache@v4
        with:
          path: ~/.haxelib
          key: ${{ runner.os }}-haxelib-${{ hashFiles('setup/build.sh') }}
          restore-keys: |
            ${{ runner.os }}-haxelib-

      - name: Install Libraries (run script)
        run: |
          bash setup/build.sh
          haxelib list

      - name: Setup Android cmdline-tools
        if: ${{ inputs.name == 'Android' }}
        uses: android-actions/setup-android@v3
        with:
          cmdline-tools-version: "12.0"
          packages: "cmdline-tools;12.0"

      - name: Install NDK + SDK packages
        if: ${{ inputs.name == 'Android' }}
        run: |
          $ANDROID_SDK_ROOT/cmdline-tools/12.0/bin/sdkmanager --sdk_root=$ANDROID_SDK_ROOT "ndk;25.2.9519653" "platform-tools" "platforms;android-16"

      - name: Configure Android
        if: ${{ inputs.name == 'Android' }}
        run: |
          echo "ANDROID_NDK_ROOT=$ANDROID_SDK_ROOT/ndk/25.2.9519653" >> $GITHUB_ENV
          echo "PATH=$PATH:$ANDROID_SDK_ROOT/ndk/25.2.9519653/toolchains/llvm/prebuilt/linux-x86_64/bin" >> $GITHUB_ENV

          haxelib run lime config ANDROID_SDK $ANDROID_SDK_ROOT
          haxelib run lime config ANDROID_NDK_ROOT $ANDROID_SDK_ROOT/ndk/25.2.9519653
          haxelib run lime config JAVA_HOME $JAVA_HOME
          haxelib run lime config ANDROID_SETUP true

      - name: Clean Android
        if: ${{ inputs.name == 'Android' }}
        run: haxelib run lime clean android

      - name: Compile
        if: ${{ inputs.name == 'Android' }}
        run: haxelib run lime build android -Dandroid-arch=armv7 ${{ inputs.buildArgs }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.artifactName }}
          path: ${{ inputs.artifactPath }}
          if-no-files-found: error