name: Build

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
      os:
        required: true
        type: string
      setupCommand:
        required: true
        type: string
      buildArgs:
        required: true
        type: string
      artifactName:
        required: true
        type: string
      artifactPath:
        required: true
        type: string

env:
  HAXE_VERSION: 4.3.2
  PROJECT_NAME: NeuroEngine
  GRADLE_OPTS: -Xmx4096m -Dorg.gradle.daemon=false
  _JAVA_OPTIONS: -Xmx4096m

jobs:
  build:
    name: Build
    runs-on: ${{ inputs.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Haxe
        uses: krdlab/setup-haxe@v1
        with:
          haxe-version: ${{ env.HAXE_VERSION }}

      - name: Cache Haxelib
        uses: actions/cache@v4
        with:
          path: ~/.haxelib
          key: ${{ runner.os }}-haxelib-${{ hashFiles('setup/build.sh') }}
          restore-keys: |
            ${{ runner.os }}-haxelib-

      - name: Install Libraries (run script)
        run: |
          bash setup/build.sh
          haxelib list

      - name: Install Android NDK r21e
        run: |
          echo "y" | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --install "ndk;21.4.7075529"
          echo "ANDROID_NDK_ROOT=$ANDROID_HOME/ndk/21.4.7075529" >> $GITHUB_ENV

      - name: Configure Android
        if: ${{ inputs.name == 'Android' }}
        run: |
          haxelib run lime config ANDROID_SDK $ANDROID_HOME
          haxelib run lime config ANDROID_NDK_ROOT $ANDROID_HOME/ndk/21.4.7075529
          haxelib run lime config JAVA_HOME $JAVA_HOME
          haxelib run lime config ANDROID_SETUP true
          
      - name: Clean Android
        if: ${{ inputs.name == 'Android' }}
        run: haxelib run lime clean android

      - name: Configure Gradle Heap
        run: |
          mkdir -p ~/.gradle
          echo "org.gradle.jvmargs=-Xmx4096m -Dfile.encoding=UTF-8" >> ~/.gradle/gradle.properties
          echo "org.gradle.daemon=false" >> ~/.gradle/gradle.properties
          
      - name: Compile
        if: ${{ inputs.name == 'Android' }}
        run: haxelib run lime build android -Dandroid-arch=arm64 -DHXCPP_STL_HTTP=libc++ ${{ inputs.buildArgs }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.artifactName }}
          path: ${{ inputs.artifactPath }}
          if-no-files-found: error
